package com.example.sosialisasik3l;

import android.app.Activity;
import android.os.Bundle;
import android.content.Intent;
import android.net.Uri;
import android.graphics.Color;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.webkit.ValueCallback;
import android.webkit.WebChromeClient;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;

public class MainActivity extends Activity {
    private WebView web;
    private FrameLayout root;
    private ValueCallback<Uri[]> upload;
    private static final int FILE_REQ = 1001;

    private static final String WEB_APP_URL =
        "https://script.google.com/macros/s/AKfycbxuEXZ55Rq1QjkERdSVgd08o2Yf4K_RtJj4y3Zi0PwlYAHK1ag5Q34780xUAgDrEZjp/exec?embedded=true";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        root = new FrameLayout(this);
        root.setBackgroundColor(Color.WHITE);

        web = new WebView(this);
        root.addView(web, new FrameLayout.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.MATCH_PARENT
        ));
        setContentView(root);

        WebSettings settings = web.getSettings();
        settings.setJavaScriptEnabled(true);
        settings.setDomStorageEnabled(true);
        settings.setAllowFileAccess(true);
        settings.setMediaPlaybackRequiresUserGesture(false);
        settings.setBuiltInZoomControls(false);
        settings.setDisplayZoomControls(false);

        web.setVerticalScrollBarEnabled(false);
        web.setHorizontalScrollBarEnabled(false);
        web.setOverScrollMode(WebView.OVER_SCROLL_NEVER);

        web.setWebViewClient(new WebViewClient() {
            @Override
            public void onPageFinished(WebView view, String url) {
                super.onPageFinished(view, url);
                hideAppsScriptBanner();
                startBannerCleaner();
            }
        });

        web.setWebChromeClient(new WebChromeClient() {
            @Override
            public boolean onShowFileChooser(
                    WebView view,
                    ValueCallback<Uri[]> callback,
                    FileChooserParams params) {

                if (upload != null) {
                    upload.onReceiveValue(null);
                }

                upload = callback;

                try {
                    Intent intent = params.createIntent();
                    startActivityForResult(intent, FILE_REQ);
                } catch (Exception e) {
                    upload = null;
                    return false;
                }

                return true;
            }
        });

        web.loadUrl(WEB_APP_URL);
    }

    /*
     * Google Apps Script adds its own warning bar outside the HTML
     * generated by Index.html. CSS in Index.html cannot remove it.
     *
     * This native WebView workaround detects the warning text and moves
     * the WebView upward by exactly the warning height, so the app content
     * starts at the top of the phone screen without changing the backend.
     */
    private void hideAppsScriptBanner() {
        final String js =
            "(function(){" +
            "function clean(){" +
            "var els=document.querySelectorAll('body *');" +
            "for(var i=0;i<els.length;i++){" +
            "var e=els[i]; var t=(e.innerText||e.textContent||'').replace(/\\s+/g,' ').trim();" +
            "if(t.indexOf('Aplikasi ini dibuat oleh pengguna')>=0 || t.indexOf('Google Apps Script')>=0 || t.indexOf('This application was created by a Google Apps Script user')>=0){" +
            "var r=e.getBoundingClientRect();" +
            "if(r.top<120 && r.height>20 && r.height<180){" +
            "e.style.setProperty('display','none','important');" +
            "e.style.setProperty('visibility','hidden','important');" +
            "}" +
            "}" +
            "}" +
            "}" +
            "clean();" +
            "setTimeout(clean,100);setTimeout(clean,300);setTimeout(clean,700);setTimeout(clean,1200);setTimeout(clean,2000);" +
            "return document.body ? document.body.innerText.indexOf('Aplikasi ini dibuat oleh pengguna') : -1;" +
            "})()";

        web.evaluateJavascript(js, value -> {});
    }

    private void startBannerCleaner() {
        web.postDelayed(new Runnable() {
            @Override public void run() {
                hideAppsScriptBanner();
                if (web != null) web.postDelayed(this, 1500);
            }
        }, 200);
    }

    @Override
    protected void onActivityResult(
            int requestCode,
            int resultCode,
            Intent data) {

        if (requestCode == FILE_REQ && upload != null) {
            Uri[] results =
                    WebChromeClient.FileChooserParams.parseResult(
                            resultCode,
                            data
                    );

            upload.onReceiveValue(results);
            upload = null;
        }

        super.onActivityResult(requestCode, resultCode, data);
    }

    @Override
    public void onBackPressed() {
        if (web.canGoBack()) {
            web.goBack();
        } else {
            super.onBackPressed();
        }
    }
}
